import Head from "next/head";
import * as React from "react";

import { CommentList } from "../components/CommentList";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <CommentList />
      </main>
    </div>
  );
}
