import Head from "next/head";
import * as React from "react";

import { Map } from "../components/Map/Map";
// import { Link } from "../components/link";
// import { UserProfile } from "../components/user-profile";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <script
          src="https://api-maps.yandex.ru/2.1/?apikey=ad7c40a7-7096-43c9-b6e2-5e1f6d06b9ec&lang=ru_RU"
          type="text/javascript"
        />
        <script
          src="https://yastatic.net/s3/mapsapi-jslibs/heatmap/0.0.1/heatmap.min.js"
          type="text/javascript"
        />
      </Head>
      {/* <div className={styles.container}>
        <main className={styles.main}>
          <h2 className={styles.title}>Welcome to DTP-MAP</h2>

          <h3>Menu:</h3>
          <Link href="/iframes/comments/1">Comments</Link>

          <h3>User profile:</h3>
          <UserProfile />
        </main>
      </div> */}
      <Map />
    </>
  );
}
